src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert; // va nous permettre de sécuriser notre formulaire


/**   
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"}, 
 *  message="Une autre annonce possède déjà ce titre, merci de le modifier."
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères !", maxMessage="Le titre ne peut pas dépasser 255 caractères !")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, max=255, minMessage="Le titre doit faire plus de {{ limit }} caractères !", maxMessage="Le titre ne peut pas dépasser {{ limit }} caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Le titre doit faire plus de {{ limit }} caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *      message = "Vous devez entrer une URL valide !")
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * Permet de faire valider le sous-formulaire
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;



    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
 
    }



    /**
     * permet d'initialiser le slug avant la persistance et avant la modification donc avant 
     * @ORM\PrePersist 
     * @ORM\PreUpdate
     * 
     * @return void
     *
     */

    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify(); // on créer une instance de la classe slugify
            $this->slug = $slugify->slugify($this->title);
        }
    }
    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     * @param User $author
     * @return comment | null
     */


    public function getCommentFromAuthor(User $author){
        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author) return $comment;
        }
        return null;
         
    }

    /**
     * Permet d'obtenir la note global d'une annonce 
     */

    public function getAvgRatings(){
        //calculer la somme des notations
        // array_reduce est une fonction qui réduit un tableau à une seule valeur
        //comments->toArray() permet de transformer notre arrayCollection comments en un array classique
        // array_reduce va boucler sur la tableau comments et va appliquer la fonction ! 
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);
        //faire la division pour avoir la moyenne
        if(count($this->comments) > 0) return $moyenne = $sum / count($this->comments);

        return 0;
    }



    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     * 
     * @return array Un tableau d'objet dateTime répresentant les jours occupées
     * 
     */

    public function getNotAvailableDays(){
        $notAvailableDays = [];

        foreach($this->bookings as $booking){
            //calculer les jours qui se trouvent entre la date d'arrivée et de départ
            // la fonction range permet d'obtenir le nombre d'élément entre 2 élément.
            // getTimestamp est une méthode qui fonctionne sur les objets de type DateTime
            //24 * 60 * 60  correspond au nombre de seconde dans une journée

            // le tableau résultat stock les dates indisponibles sous la forme de gros nombre

            $resultat = range($booking->getStartDate()->getTimestamp(), 
            $booking->getEndDate()->getTimestamp(), 24 * 60 * 60 );
        

        // dans le tableau days, on a convertir notre tableau résultat avec de réel date d'indisponibilité
           $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
           }, $resultat);

           // on fusionne deux tableaux, dont plus la boucle avance, plus le tableau notAvailableDays s'enrichit
           $notAvailableDays = array_merge($notAvailableDays, $days);
    }
           return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }


}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ImageType;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends ApplicationType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        // utilisation de la fonction add de la manière normale
            ->add('title', TextType::class, [
                'label' => 'Titre',
                'attr' => [
                    'placeholder' => "Tapez un super titre pour votre annonce"
                ] 
            ])

            // utilisation de la fonction getconfiguration pour faciliter le code
            ->add('slug', TextType::class, $this->getconfiguration("Adresse Web", "Tapez l'adresse Web (automatique)", [
                'required' => false 
            ]))

            ->add('coverImage', UrlType::class, $this->getconfiguration("Url de l'image principale", "donnez l'adresse d'une image qui donne vraiment envie !"))

            ->add('introduction', TextType::class, $this->getconfiguration("Introduction", "Donnez une description globale de l'annonce"))

            ->add('content', TextareaType::class, $this->getconfiguration("Description détaillée", "Tapez une description qui donne vraiment envie de venir chez vous"))

            ->add('rooms', IntegerType::class, $this->getconfiguration("Nombre de chambre", "Le nombre de chambre disponibles "))

            ->add('price',MoneyType::class, $this->getconfiguration("Prix par nuit", "Indiquez le prix que vous souhaitez pour une nuit" ) )
                    
            ->add('images', 
                    CollectionType::class, 
                    [
                        'entry_type' => ImageType::class,
                        'allow_add' => true,
                        'allow_delete' => true /* permet de supprimer des éléments du CollectionType */
                    ]
                    )
                    ;
        }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class

        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;

use App\Repository\AdRepository;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads/{page}", name="ads_index", requirements={"page": "\d+"})
     */
    public function index(AdRepository $repo, $page = 1): Response
    {
            // Permet de faire la pagination
            $limit = 9;
            $start = $page * $limit - $limit;
            $total = count($repo->findAll());
            $pages = ceil($total / $limit);
       /*  $repo = $this->getDoctrine()->getRepository(Ad::class); */ // cette ligne me permet de récupérer le repository qui gère les annonces.

        return $this->render('ad/index.html.twig', [
            
                'ads' => $repo->findBy([], [],$limit, $start),
                'pages' => $pages,
                'page' => $page
        ]);
    }

    /**
     * Permet de créer une annonce 
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     * @return Response
     */

    public function create(Request $request){
        $ad = new Ad();

       /*  $request->request->get('title'); // permet de récupérer le titre dans le formulaire  */
        $form = $this->createForm(AdType::class, $ad);   

        $form->handleRequest($request); //cette fonction permet de récupérer la requête et d'extraire les informations du form. On lui passe la requête http

        if($form->isSubmitted() && $form->isValid()){


            $manager = $this->getDoctrine()->getManager();

            foreach($ad->getImages() as $image){
                $image->setAd($ad); 
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());
           
            $manager->persist($ad); // manager fait persister mon annonce dans le temps
            $manager->flush(); // envoi ma requête sql en base de données

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !"
            );
  
            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }
        
        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le formulaire d'édition 
     * 
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier !")
     * 
     * @return Response
     */

    public function edit(Ad $ad, Request $request){
    
        $form = $this->createForm(AdType::class, $ad);   

        $form->handleRequest($request); 

        if($form->isSubmitted() && $form->isValid()){


            $manager = $this->getDoctrine()->getManager();

            foreach($ad->getImages() as $image){
                $image->setAd($ad); 
                $manager->persist($image);
            }
           
            $manager->persist($ad); // manager fait persister mon annonce dans le temps
            $manager->flush(); // envoi ma requête sql en base de données

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été modifiées !"
            );
  
            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        
        return $this->render("ad/edit.html.twig", [
            'form' => $form->createView(),
            'ad' => $ad 
        ]

    );
    }


    /**
     * Permet d'afficher une seule annonce
     * 
     * @Route("/ads/{slug}", name="ads_show")
     * @return Response
     * 
     */

    public function show(Ad $ad){

        return $this->render('ad/show.html.twig', 
        [
            'ad'=> $ad 
        ]);
    }

    /**
     * Permet de supprimer une annonce
     * 
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message ="Vous n'avez pas le droit d'accéder à cette ressource")
     * @return Response
     * 
     */

    public function delete(Ad $ad){
        $manager = $this->getDoctrine()->getManager();
        
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success', 
            "L'annone <strong>{$ad->getTitle()}</strong> a bien été supprimée");
        

        return $this->redirectToRoute("ads_index");


    }



}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug' : ad.slug}) %}
<div class="col-12 col-lg-4">

    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ad.rooms}} chambres, <strong>{{ad.price | number_format(2,',', ' ')}}€</strong><br>
            {% if ad.comments | length > 0 %}
                {% include "partials/rating.html.twig" with {'rating' : ad.avgRatings} %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <a href="{{url}}">
            <img src="{{ad.coverImage}}" alt="image de l'appartement" style="height: 200px; width: 100%; display:block" >
        </a>
        <div class="card-body">
            <a href="{{url}}">
                <h4 class="card-title">
                    {{ ad.title}}
                </h4> 
            </a>
            <p class="card-text">
                {{ad.introduction}}
            </p>

            <a class="btn btn-primary" href="{{url}}">En savoir plus !</a>
            {% if(app.user and app.user == ad.author)%}
            <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %} {# permet de modifier la sortie de form_widget() sur  un champ donné #}
    <p>Ici, vous pouvez ajoputer vos propres images : </p>

    <input type="hidden" id="widgets-counter" value="0">

    {{ form_widget(form) }}

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Ajouter une image
            </button>
    </div>

{% endblock %}

{% block _ad_images_entry_row %} {# la row contient le label, les erreurs, le widget et les aides #}

     {{ form_widget(form) }}

{% endblock %}

{% block _ad_images_entry_widget %} 
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                         {{form_errors(form.url)}} {# permet d'afficher les erreurs #}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption)}}
                        {{form_errors(form.caption)}} {# permet d'afficher les erreurs #}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger"> X </button>
            </div>
        </div>
    </div>

{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title  %}Edition d'une annonce {% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Modifier l'annonce : {{ad.title}} </h1>

        {{ form_start(form)}}

        {{form_widget(form)}}

         <button type="submit" class="btn btn-primary">Mettre à jour vos informations</button>

        {{form_end(form)}}
    </div>
{% endblock %}
{# test 2 #}

{% block javascripts %}
<script src="/js/ad.js"></script>

{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos supers annonces{% endblock %}

{% block body %}
<div class="container mt-3">
    <h1 class="my-5">Les annonces de nos hotes</h1>
    <div class="row">
        {% for ad in ads %}
            {% include "ad/_ad.html.twig" %}
        {% endfor %}
    
    </div>
     {% include 'admin/partials/pagination.html.twig' with {'route' : 'ads_index'}%}
     
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce {% endblock %}

{% form_theme form 'ad/_collection.html.twig' %} {# form_theme permet de rendre au courant twig que nous voulons utiliser un theme particulier #}


{% block body %}
    <div class="container">
        <h1 class="my-5">Créer une nouvelle annonce</h1>

        {{ form_start(form)}}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Informations générales</h2>
                    <hr>
                    {{form_row(form.title)}}
                    {{form_row(form.slug)}}
                    {{form_row(form.price)}}
                    {{form_row(form.rooms)}}
                </div>

            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2>Image de l'annonce</h2>
                    <hr>
                    {{form_row(form.coverImage)}}
                    {{form_row(form.images)}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="alert alert-light">
                    <h2>Détails de l'annonce</h2>
                    <hr>
                    {{form_row(form.introduction)}}
                    {{form_row(form.content)}}
                </div>
            </div>
        </div>
        <div class="alert alert-success clearfix">
            <h2 class="alert-heading">Sauvegarder mon annonce</h2>
            <p>Vous êtes sur le point de créer votre annonce, nous sommes fière de vous ! </p>
            <button type="submit" class="btn btn-primary float-right"><i class="fas fa-check"></i> Créer une nouvelle annonce</button>
            
        </div>


        {{form_end(form)}}
    </div>
{% endblock %}

{% block javascripts %}
<script src="/js/ad.js"></script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}

    {{ad.title}}
{% endblock %}

{% block body %}

    <div class="ad-title" style="background-image : url({{ad.coverImage}})">
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p class="h2">
                <strong>{{ad.rooms}} chambres</strong> pour <strong>{{ad.price | number_format(2,',', ' ')}}€</strong> par nuit
            </p>
            <a href="{{ path('booking_create', {'slug' : ad.slug })}}" class="btn btn-primary">Réserver !</a>

            {% if(app.user and app.user == ad.author)%}
            <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
            <a href="{{ path('ads_delete', {'slug' : ad.slug})}}" class="btn btn-danger" onclick="return confirm (`Êtes-vous sûr de vouloir supprimer l'annonce : {{ad.title}} ?` )">Supprimer l'annonce</a>

            {% endif %}
        </div>
    </div>

    <div class="container">
       <div class="row">
            <div class="col-md-8 mb-3">
                {{ad.content | raw}}

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0}}" class="{% if loop.first %}active {% endif %}"></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                    <div class="carousel-item {% if loop.first %}active {% endif %}">
                    <img src="{{ image.url}}" class="d-block w-100" alt="...">
                     <div class="carousel-caption d-none d-md-block">
                        <h5>{{ad.title}}</h5>
                        <p>{{ image.caption}}</p>
                    </div>
                    </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </div>
                <hr>

                {% if ad.comments| length > 0 %}
                    <h2 class="mb-3">Commentaires de nos voyageurs :</h2>
                    <div class="alert alert-info">
                        <h4 class="alert alert-heading text-center">
                            <div class="row align-items-center">
                                <div class="col">
                                    Note Global par nos voyageurs<br>
                                    
                                </div>
                                <div class="col">
                                    {% include "partials/rating.html.twig" with { 'rating'  : ad.avgRatings} %}<br>
                                    <small>Calculée sur {{ad.comments | length}} avis !</small>
                                </div>
                            </div>
                        </h4>
                    </div>
                    {% for comment in ad.comments %}
                        <div class="bg-light rounded mb-3 py-3 px-3">
                            <strong>{{comment.author.firstName}}</strong> a dit :
                            <blockquote>
                                {{comment.content}}
                            </blockquote>
                            <strong>Note donnée : </strong> 
                            {% include "partials/rating.html.twig" with {'rating' : comment.rating} %}
                        </div>
                    {% endfor %}
                    {% else %}
                        <h2>Cette annonce n'a pas de commentaires ....</h2>
                {% endif %}
            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row">
                    <div class="col-4 mr-3">
                        <a href="{{path('user_show', {'slug' : a.slug })}}">
                            <img src="{{ad.author.picture }}" alt="avatar de {{ a.FullName() }}" class="avatar avatar-medium">
                        </a>
                    </div>
                    <div class="col">
                        <a href="{{path('user_show', {'slug' : a.slug })}}" style="text-decoration : none">
                            <h3>{{a.FullName()}}</h3>
                        </a>
                        <span class="badge badge-primary">{{a.ads | length}} annonces</span>
                    </div>
                </div> 
                {{ a.description  | raw }}
         
            </div>
        </div>
    </div>

{% endblock %}